version: "3.8"

services:
  database:
    container_name: akademikaracom-db
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - akademikaracom-db-data:/var/lib/mysql
      - ./mysql_backups:/backup
    networks:
      akademikaracom-network:

  app:
    container_name: akademikaracom
    image: mhmmddzgn/akademikaracom:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_PASS=${DB_PASS}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL}
    networks:
      akademikaracom-network:
    restart: on-failure

volumes:
  akademikaracom-db-data:

networks:
  akademikaracom-network: